# Workspace 1
windowrule = workspace 1 silent, class:Code, title:Visual Studio Code

# Workspace 2
windowrule = workspace 2 silent, class:vivaldi-stable

# Workspace 4
windowrule = workspace 4 silent, class:discord
windowrule = workspace 4 silent, class:org.telegram.desktop
windowrule = workspace 4 silent, class:wasistlos

# Workspace 5
windowrule = workspace 5, class:^(steam_app_default)$, title:^(World of Warcraft)$

# Workspace 6
# windowrule = workspace 6, class:net.lutris.Lutris
# windowrule = workspace 6, class:tsmapplication.exe
# windowrule = workspace 6, class:CurseForge
# windowrule = workspace 6, class:^(steam_app_default)$, title:^(Battle\.net)$

# Workspace 7
windowrule = workspace 7, class:Tor Browser

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# XWayland video bridge window rules
windowrule = opacity 0.0 override, class:xwaylandvideobridge
windowrule = noanim, class:xwaylandvideobridge
windowrule = noinitialfocus, class:xwaylandvideobridge
windowrule = maxsize 1 1, class:xwaylandvideobridge
windowrule = noblur, class:xwaylandvideobridge
windowrule = nofocus, class:xwaylandvideobridge

# Change to default tiling
windowrule = float, class:tsmapplication.exe
windowrule = center, class:tsmapplication.exe
windowrule = tile, class:^(steam_app_default)$

windowrule = float,class:org.pulseaudio.pavucontrol
windowrule = center,class:org.pulseaudio.pavucontrol

windowrule = float, class:blueman-manager
windowrule = center, class:blueman-manager

windowrule = float, class:nm-connection-editor
windowrule = center, class:nm-connection-editor

windowrule = float, class:org.qbittorrent.qBittorrent
windowrule = center, class:org.qbittorrent.qBittorrent

windowrule = float, class:input-remapper-gtk
windowrule = center, class:input-remapper-gt

windowrule = float, class:waypaper
windowrule = center, class:waypaper

windowrule = float, class:org.kde.filelight
windowrule = center, class:org.kde.filelight

windowrule = float, class:GParted
windowrule = center, class:GParted

windowrule = float, class:polychromatic
windowrule = center, class:polychromatic

windowrule = float, class:Tk
windowrule = center, class:Tk

windowrule = float, class:Tor Browser

windowrule = float, class:python3, title:Tor Browser Launcher Einstellungen

windowrule = float, class:filezilla
windowrule = center, class:filezilla
windowrule = size 1330x800, class:filezilla

layerrule = dimaround, wofi

windowrule = float, class:steam
windowrule = workspace 6, class:steam

windowrule = float, class:qalculate-gtk

windowrule = float, class:kitty, title:Notes
windowrule = center, class:kitty, title:Notes

windowrule = float, class:org.clipgrab.clipgrab
windowrule = center, class:org.clipgrab.clipgrab

windowrule = tile, class:libreoffice-calc
windowrule = tile, class:libreoffice-writer

windowrule = float, class:wshowkeys

windowrule = float, class:kitty, title:calcurse