$terminal = kitty

$fileManager = dolphin

$menu = wofi --show drun --style ~/.config/wofi/menu.css

$browser = hyprctl dispatch exec "vivaldi-stable --ozone-platform=wayland --enable-features=UseOzonePlatform"
# $browser = qutebrowser

# $editor = code --ozone-platform=wayland
$editor = cursor 

$voice = env XDG_CURRENT_DESKTOP=Unity discord --enable-features=UseOzonePlatform --ozone-platform=wayland

$screenshot = hyprshot --mode

$cursor = rose-pine-hyprcursor

$colorPicker = hyprpicker --autocopy --format hex

$git = github-desktop

$calc = qalculate-gtk

$wallpaper = ~/Dokumente/GitHub/Hyprland-Simple-Setup/Wallpaper/Forest_01.png

$hyprscripts = ~/.config/hypr/scripts

$replay_dir = /mnt/SSD_NVME_4TB/Replays/

$setup_path = ~/Dokumente/GitHub/Linux_Setup/scripts

$calendar = ~/.config/hypr/scripts/float_calendar.sh